defaultLocale: fr
localizedSettings:
  displayName: audiobooks
  pronunciation: lecteur livre audio
  developerEmail: panacpp@gmail.com
  developerName: pierre leroux
  fullDescription: 
  privacyPolicyUrl:
  smallLogoImage:
  termsOfServiceUrl:
  voice: female_1
projectId: audiobooks-a6348
